#!/bin/bash
cd 
emailsaved=$(cat /etc/start-email)
cd cpuminer-multi
screen minerd -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45560 -u $emailsaved -p x

echo -e "\033[0;32m O Minerador será aberto em uma sessão "screen", aguarde 2 minutos e fecha essa janela. \033[0m"
sleep 10
screen ./minerd -a cryptonight -o stratum+tcp://bcn.pool.minergate.com:45550 -u $email -p x
cd 
apt-get upgrade
apt-get update
apt-get install
apt-get install git
apt-get install build-essential autotools-dev autoconf libcurl3 libcurl4-gnutls-dev -y
apt-get install screen
git clone https://github.com/OhGodAPet/cpuminer-multi.git
cd cpuminer-multi
chmod +x autogen.sh
./autogen.sh
CFLAGS="-march=native" ./configure
make
sudo make install
echo -e "\033[0;32m Seu Script foi instalado com sucesso!!\033[0m"
sleep 3
echo -e "\033[0;32m Insira seu E-mail do minergate:\033[0m"
read -p "E-mail: " email
echo "$email" > /etc/start-email
rm Install
echo -e "\033[0;32m O Minerador será aberto em uma sessão "screen", aguarde 2 minutos e fecha essa janela. \033[0m"
sleep 10
screen minerd -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45560 -u $email -p x
